source 'https://rubygems.org'

gem 'aws-sdk', '~> 2.3.8'
gem 'cf-uaa-lib', '~> 3.11.0'
gem 'cf-uaac', '~> 4.2.0'
gem 'colorize', '~> 0.8.1'
gem 'github_merge_sign', '1.0.0'
gem 'govuk-lint', '~> 3.8.0'
gem 'govuk-registers-api-client'
gem 'hcl-checker', '~>1.1.1'
gem 'json-minify', '~> 0.0.2'
gem 'mail', '~> 2.6.4'
gem 'rest-client', '~> 2.1.0'
gem 'rspec', '~> 3.3'
gem 'rubocop', '~> 0.52.1'
gem 'simplecov', require: false, group: :test
gem 'webmock', '~> 2.3.1'
gem 'levenshtein', '0.2.2'
gem 'tty-prompt'
