source "https://rubygems.org"

gem "addressable", ">= 2.8.0"
gem "aws-sdk", "~> 3"
gem "cf-uaac", "~> 4"
gem "cf-uaa-lib", "~> 3.11.0"
gem "colorize", "~> 0.8.1"
gem "fuzzy_match", "~> 2.1"
gem "govuk-registers-api-client"
gem "http", "~> 4"
gem "json-minify", "~> 0.0.3"
gem "mail", "~> 2.7"
gem "notifications-ruby-client", "~> 5"
gem "rake", "~> 12"
gem "rest-client", "~> 2.1.0"
gem "rexml", ">= 3.2.5"
gem "rspec", "~> 3"
gem "rubocop-govuk", "~> 3.15"
gem "simplecov", require: false, group: :test
gem "tty-prompt"
gem "webmock", "~> 2"
