source "https://rubygems.org"

gem "aws-sdk", "~> 3"
gem "cf-uaa-lib", "~> 3.11.0"
gem "cf-uaac", "~> 4.2.0"
gem "colorize", "~> 0.8.1"
gem "fuzzy_match"
gem "govuk-registers-api-client"
gem "hcl-checker", "~>1.1.1"
gem "http", "~> 4.4"
gem "json-minify", "~> 0.0.2"
gem "mail", "~> 2.6.4"
gem "notifications-ruby-client", "~> 5.1"
gem "rake", "~> 12.3.3"
gem "rest-client", "~> 2.1.0"
gem "rspec", "~> 3.3"
gem "rubocop-govuk", "~> 3.15"
gem "simplecov", require: false, group: :test
gem "tty-prompt"
gem "webmock", "~> 2.3.1"
