# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = ENV['VAGRANT_BOX_NAME'] || 'aws_vagrant_box'

  Dir.glob("./post-deploy.d/*").sort.each do |post_deploy_file|
    config.vm.provision "shell" do |s|
      s.privileged = true
      s.env = ENV.select {
        |key| ['CONCOURSE_ATC_PASSWORD', 'CONCOURSE_ATC_USER'].include? key
      }
      s.name = post_deploy_file
      s.path = post_deploy_file
    end
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.associate_public_ip = true
    aws.tags = { 'Name' => (ENV['DEPLOY_ENV'] || ENV['USER']) + " concourse" }

    # The Concourse AMI is currently only available in us-east-1, this is v. 0.70
    aws.ami = 'ami-5c104436'
    aws.region = 'us-east-1'

    # Only HVM instances with ephemeral disks can be used
    aws.instance_type = 'm3.large'

    # us-east-1e in default VPC, 172.31.0.0/20 range
    aws.subnet_id = 'subnet-b2e3a488'

    # "Concourse Vagrant" security group
    aws.security_groups = ['sg-ee21a597']

    # Add IAM role to allow access to necessary AWS APIs
    aws.iam_instance_profile_name = 'bootstrap-concourse'

    # We will rely on vagrant generating a ssh key, but this must be the ubuntu user, as the vagrant user does not exist on the vm
    override.ssh.username = "ubuntu"

    # Fix issue on osx: https://github.com/mitchellh/vagrant/issues/5401#issuecomment-115240904
    override.nfs.functional = false
  end

end
