aws_account = "ci"
system_dns_zone_id = "Z1SXW0ZFXE9V93"
system_dns_zone_name = "ci.paas.alphagov.co.uk"
apps_dns_zone_id = "Z1CO8TXZC0D3CL"
apps_dns_zone_name = "ci-apps.paas.alphagov.co.uk"
cf_db_multi_az = "false"
cf_db_backup_retention_period = "0"
skip-final-snapshot = "true"
