aws_account = "dev"
system_dns_zone_id = "Z1TAH54WN7GPLT"
system_dns_zone_name = "dev.paas.alphagov.co.uk"
apps_dns_zone_id = "Z2M760FEEY23BS"
apps_dns_zone_name = "dev-apps.paas.alphagov.co.uk"
cf_db_multi_az = "false"
cf_db_backup_retention_period = "0"
cf_db_skip_final_snapshot = "true"
