aws_account = "dev"
system_dns_zone_id = "Z1QGLFML8EG6G7"
apps_dns_zone_id = "Z3R6XFWUT4YZHB"
cf_db_multi_az = "false"
cf_db_backup_retention_period = "0"
cf_db_skip_final_snapshot = "true"
web_access_cidrs = "0.0.0.0/0"
tenant_cidrs = "52.19.165.187/32"