aws_account = "prod"
system_dns_zone_id = "updateme_prod_system_zone_id"
system_dns_zone_name = "updateme_prod_system_zone_name"
apps_dns_zone_id = "updateme_prod_apps_zone_id"
apps_dns_zone_name = "updateme_proc_apps_zone_name"
cf_db_multi_az = "true"
cf_db_backup_retention_period = "35"
cf_db_skip_final_snapshot = "false"
