aws_account = "stage"
system_dns_zone_id = "ZPFAUK62IO6DS"
system_dns_zone_name = "staging.cloudpipeline.digital"
apps_dns_zone_id = "Z32JRRSU1CAFE8"
apps_dns_zone_name = "staging.cloudpipelineapps.digital"
cf_db_multi_az = "true"
cf_db_backup_retention_period = "35"
cf_db_skip_final_snapshot = "false"
