{
 "title": "Billing Performance",
 "description": "terrible dashboard with some performance metrics from billing",
 "tags": [ "billing" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Collector: runSQLFile time taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(paas_billing_eventstore_performance{job=\"billing-collector\", function=~\"runSQLFile.*\"}, \"filename\", \"$2\", \"function\", \"(.*):(.*)\")",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Function Durations (EventCollector)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(functionname, job) (label_replace(\n  paas_billing_eventstore_performance,\n  \"functionname\",\n  \"$1\",\n  \"function\",\n  \"^(.*?)(:|$).*$\"\n))",
     "legendFormat": "{{functionname}} ({{job}})"
    }
   ]
  },
  {
   "title": "Function Durations (EventStore)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(functionname, job) (label_replace(\n  paas_billing_eventstore_performance,\n  \"functionname\",\n  \"$1\",\n  \"function\",\n  \"^(.*?)(:|$).*$\"\n))",
     "legendFormat": "{{functionname}} ({{job}})"
    }
   ]
  },
  {
   "title": "Function Durations (CFEventFetcher)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(functionname, job) (label_replace(\n  paas_billing_cfeventfetcher_performance,\n  \"functionname\",\n  \"$1\",\n  \"function\",\n  \"^(.*?)(:|$).*$\"\n))",
     "legendFormat": "{{functionname}} ({{job}})"
    }
   ]
  }
 ]
}