{
 "title": "Billing compared to spending (new billing metrics)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "exchange_rate", "label": "Exchange rate", "query": "0.8" }
  ]
 },
 "panels": [
  {
   "title": "Proportion of AWS EC2 costs billed / week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"app\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate)",
     "legendFormat": "Proportion of AWS EC2 costs billed (7 day rolling average) (old)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"app\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate)",
     "legendFormat": "Proportion of AWS EC2 costs billed (7 day rolling average) (new)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"app\"}[7d]))",
     "legendFormat": "Compute billed / week"
    },
    {
     "expr": "sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate",
     "legendFormat": "AWS EC2 costs / week (old)"
    },
    {
     "expr": "sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate",
     "legendFormat": "AWS EC2 costs / week (new)"
    }
   ]
  },
  {
   "title": "Proportion of AWS RDS costs billed  / week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"mysql|postgres\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of RDS costs billed (7 day rolling average) (old)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"mysql|postgres\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of RDS costs billed (7 day rolling average) (new)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"mysql|postgres\"}[7d]))",
     "legendFormat": "RDS billed / week"
    },
    {
     "expr": "sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d])) * 7 * $exchange_rate",
     "legendFormat": "AWS RDS costs / week (old)"
    },
    {
     "expr": "sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d])) * 7 * $exchange_rate",
     "legendFormat": "AWS RDS costs / week (new)"
    }
   ]
  },
  {
   "title": "Proportion of AWS Redis costs billed / week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"redis\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of AWS Redis spend billed (7 day rolling average) (old)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"redis\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of AWS Redis spend billed (7 day rolling average) (new)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"redis\"}[7d]))",
     "legendFormat": "Redis billed / week"
    },
    {
     "expr": "(sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "AWS Redis spend / week (old)"
    },
    {
     "expr": "(sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "AWS Redis spend / week (new)"
    }
   ]
  },
  {
   "title": "Proportion of AWS S3 costs billed  / week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"aws-s3-bucket\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of S3 costs billed (7 day rolling average) (old)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"aws-s3-bucket\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Proportion of S3 costs billed (7 day rolling average) (new)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"aws-s3-bucket\"}[7d]))",
     "legendFormat": "S3 billed / week"
    },
    {
     "expr": "(sum(avg_over_time(paas_aws_cost_explorer_by_service_pounds{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "AWS S3 costs / week (old)"
    },
    {
     "expr": "(sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "AWS S3 costs / week (new)"
    }
   ]
  },
  {
   "title": "Proportion of Aiven costs billed / day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"elasticsearch|opensearch|influxdb\"}[1d])) / sum(delta(paas_aiven_estimated_cost_pounds[1d])) > 0",
     "legendFormat": "Proportion of Aiven costs billed (1 day rolling average)"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"elasticsearch|opensearch|influxdb\"}[1d]))",
     "legendFormat": "Aiven billed / day"
    },
    {
     "expr": "sum(delta(paas_aiven_estimated_cost_pounds[1d])) > 0",
     "legendFormat": "Aiven costs / day"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "options": {
    "content": "\n## Note about Aiven / Elasticsearch bills\n\nBecause Aiven don't split their invoices between regions, the Aiven bill is for London _and_ Ireland combined.\n\nTo get an idea of how much we're recharging you have to look at both regions.\n\n\n\n"
   }
  }
 ]
}