{
 "title": "Billing SLIs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "exchange_rate", "label": "Exchange rate", "query": "0.8" }
  ]
 },
 "panels": [
  {
   "title": "API response time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(paas_billing_api_performance_elapsed_seconds)"
    }
   ]
  },
  {
   "title": "Billing smoke tests passing",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(concourse_builds_finished{exported_job=\"continuous-billing-smoke-tests\", status=\"succeeded\"}[1h])) / sum(increase(concourse_builds_finished{exported_job=\"continuous-billing-smoke-tests\"}[1h]))"
    }
   ]
  },
  {
   "title": "Slowest collector job performance",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(paas_billing_collector_performance_elapsed_seconds)"
    }
   ]
  },
  {
   "title": "Proportion of AWS costs billable",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "( sum(delta(paas_billing_total_costs_pounds{name=\"app\"}[7d]))+ sum(delta(paas_billing_total_costs_pounds{name=~\"mysql.+|postgres.+\"}[7d]))+ sum(delta(paas_billing_total_costs_pounds{name=~\"redis.+\"}[7d]))+ sum(delta(paas_billing_total_costs_pounds{name=\"aws-s3-bucket default\"}[7d]))) / (( sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))+ sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d]))+ sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))+ sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[7d])))*7*$exchange_rate)"
    }
   ]
  },
  {
   "title": "Proportion of 3rd party costs billed (7 day rolling average)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Compute / AWS EC2",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(delta(paas_billing_total_costs_pounds{name=\"app\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate)",
     "legendFormat": "Compute / AWS EC2",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "b",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(delta(paas_billing_total_costs_pounds{name=~\"mysql.+|postgres.+\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Database / AWS RDS",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum(delta(paas_billing_total_costs_pounds{name=~\"redis.+\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Redis / AWS Elasticache"
    },
    {
     "expr": "sum(delta(paas_billing_total_costs_pounds{name=\"aws-s3-bucket default\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "S3 / AWS S3"
    },
    {
     "expr": "sum(delta(paas_billing_total_costs_pounds{name=~\"elasticsearch.+\"}[7d])) / sum(delta(paas_aiven_estimated_cost_pounds[7d])) > 0",
     "legendFormat": "Elasticsearch / Aiven (note - regions not separated)"
    }
   ]
  }
 ]
}