{
 "title": "Billing SLIs",
 "tags": [ "billing" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "exchange_rate", "label": "Exchange rate", "query": "0.8" }
  ]
 },
 "panels": [
  {
   "title": "API response time (90th Percentile)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(echo_request_duration_seconds_sum{app_name!=\"\", url=~\"/(usage|billable)_events\"})/sum(echo_request_duration_seconds_count{url=~\"/(usage|billable)_events\", app_name!=\"\"})",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Billing smoke tests passing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(concourse_builds_finished{exported_job=\"continuous-billing-smoke-tests\", status=\"succeeded\"}[1h])) / sum(increase(concourse_builds_finished{exported_job=\"continuous-billing-smoke-tests\"}[1h]))"
    }
   ]
  },
  {
   "title": "Slowest collector job performance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, avg by (function) (paas_billing_eventstore_performance{job=\"billing-collector\"}))",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Proportion of AWS costs billable",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  (\n          sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"app\"}[1w]))\n        +\n          sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"mysql|postgres\"}[1w]))\n      +\n        sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"redis\"}[1w]))\n    +\n      sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"aws-s3-bucket\"}[1w]))\n  )\n/\n  (\n        (\n                sum(\n                  avg_over_time(\n                    paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[1w]\n                  )\n                )\n              +\n                sum(\n                  avg_over_time(\n                    paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[1w]\n                  )\n                )\n            +\n              sum(\n                avg_over_time(\n                  paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[1w]\n                )\n              )\n          +\n            sum(\n              avg_over_time(\n                paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[1w]\n              )\n            )\n        )\n      *\n        7\n    *\n      0.8\n  )"
    }
   ]
  },
  {
   "title": "Dummy Plans Created",
   "type": "stat",
   "description": "generateMissingPlans creates dummy plans with 0 cost at the epoch time\nfor every single plan in events, unless there is already one.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(paas_billing_eventstore_dummy_plans_created{job=\"billing-collector\"})"
    }
   ]
  },
  {
   "title": "Proportion of 3rd party costs billed (7 day rolling average)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Compute / AWS EC2",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"app\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Elastic Compute Cloud - Compute\"}[7d]))*7*$exchange_rate)",
     "legendFormat": "Compute / AWS EC2",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "b",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"mysql|postgres\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Relational Database Service\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Database / AWS RDS",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"redis\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon ElastiCache\",type=\"AmortizedCost\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "Redis / AWS Elasticache"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=\"aws-s3-bucket\"}[7d])) / (sum(avg_over_time(paas_aws_cost_explorer_by_service_dollars{service=\"Amazon Simple Storage Service\"}[7d]))* 7*$exchange_rate)",
     "legendFormat": "S3 / AWS S3"
    },
    {
     "expr": "sum(delta(paas_billing_eventstore_total_cost_gbp{kind=~\"elasticsearch|opensearch|influxdb\"}[7d])) / sum(delta(paas_aiven_estimated_cost_pounds[7d])) > 0",
     "legendFormat": "Elasticsearch / Aiven (note - regions not separated)"
    }
   ]
  }
 ]
}