{
 "title": "Cell memory",
 "tags": [
  "cf",
  "diego"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(bosh_job_healthy, environment)"
    }
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
    }
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
    }
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\".*diego-cell.*\"}, bosh_job_name)"
    }
   },
   {
    "name": "bosh_job_id",
    "label": "bosh_job_id",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "label": "bosh_job_ip",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
    }
   },
   {
    "name": "zone",
    "label": "zone",
    "query": {
     "query": "label_values(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cell available memory ratio (advertised/actual)",
   "type": "heatmap",
   "description": "Available memory advertised by a Rep divided by the actual available memory on its cell.\n\nA value much greater than 100% suggests a cell that might be in danger of running out of actual memory, resulting in app memory going into swap or apps unexpectedly crashing due to machine OOM.\n\nA value much lower than 100% suggests a cell that will probably stop accepting new app instances when it still has plenty of actual memory left, which is suboptimal but safe.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1e6 * firehose_value_metric_rep_capacity_remaining_memory{bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} / on(bosh_job_ip) avg(label_replace(node_memory_MemAvailable_bytes, \"bosh_job_ip\", \"$1\", \"instance\", \"(.*):.*\")) by (bosh_job_ip)"
    }
   ]
  },
  {
   "title": "Candidate cells per app size",
   "type": "graph",
   "description": "Number of cells claiming to have capacity for different memory-sizes of app",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} > 2048)",
     "legendFormat": "2G"
    },
    {
     "expr": "count(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} > 4096)",
     "legendFormat": "4G"
    },
    {
     "expr": "count(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} > 8192)",
     "legendFormat": "8G"
    },
    {
     "expr": "count(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} > 16384)",
     "legendFormat": "16G"
    },
    {
     "expr": "count(firehose_value_metric_rep_capacity_remaining_memory{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"} > 24576)",
     "legendFormat": "24G"
    },
    {
     "expr": "firehose_value_metric_bbs_present_cells{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\"}",
     "legendFormat": "BBS present cells (all)"
    }
   ]
  },
  {
   "title": "Cell memory-debt",
   "type": "heatmap",
   "description": "Amount of memory a cell has promised to apps but doesn't actually have. If all containers on the cell decided to use all their memory at the same time, this is the amount that would either get pushed into swap or start to cause unexpected OOM crashes for tenants.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1e6 * firehose_value_metric_rep_capacity_allocated_memory{bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\", zone=~\"$zone\"}) - on(bosh_job_ip) avg(label_replace(node_memory_MemTotal_bytes, \"bosh_job_ip\", \"$1\", \"instance\", \"(.*):.*\")) by (bosh_job_ip)"
    }
   ]
  },
  {
   "title": "Detailed (expensive)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container ages",
     "type": "heatmap",
     "description": "Underlying metric appears quite spotty at short timescales, with some containers disappearing and then reappearing later in seemingly impossible ways",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(firehose_value_metric_rep_container_age{bosh_job_name=~\"$bosh_job_name\", bosh_job_ip=~\"$bosh_job_ip\", bosh_job_id=~\"$bosh_job_id\"} and on(bosh_job_id) firehose_value_metric_rep_capacity_remaining_memory{zone=~\"$zone\"}) by (process_instance_id)"
      }
     ]
    },
    {
     "title": "Container sizes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg(firehose_container_metric_memory_bytes_quota{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$bosh_job_name\", bosh_job_id=~\"$bosh_job_id\", bosh_job_ip=~\"$bosh_job_ip\"} and on(bosh_job_id) firehose_value_metric_rep_capacity_remaining_memory{zone=~\"$zone\"}) by (application_id, instance_index, bosh_job_id)"
      }
     ]
    }
   ]
  }
 ]
}