{
 "title": "Component Indicators - __DEPLOY_ENV__",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "content": "#  Components\n\n***Routing*** - apps should be able to receive traffic from end users\n\n***API*** -  users should be interact with our API via the CLI and Pazmin\n\n***Scheduling*** - apps and tasks should be scheduled and run\n\n***Logging*** - users should be able to read and consume their logs\n\n***Service discovery*** - apps should be able to discover and talk to other apps"
  },
  {
   "title": "Jargon",
   "type": "text",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "content": "# Components\n\n- Cell - a server which runs apps (LRPs) and tasks for users\n- LRP - long running process\n- RLP - Reverse Log Proxy\n- UAA - User accounts & authentication server"
  },
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 9 },
   "content": "# Routing\n\nSee [`indicators.yml`](https://github.com/cloudfoundry/routing-release/blob/release/jobs/gorouter/templates/indicators.yml.erb)\n\n## Route registration receipt %\n\nIf route registration messages are not received by gorouter, then users will see 404s.\n\nThis can be >100% because of how the metrics are collected from distributed components. In the long run it should be 100%\n\n## Route registration latency\n\nIf route registration messages are not broadcast in a timely fashion, then users will see 404s.\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Receipt % 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 9 },
   "repeat": "Interval",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(firehose_counter_event_gorouter_registry_message_route_emitter_total[24h])+rate(firehose_counter_event_gorouter_unregistry_message_route_emitter_total[24h]))) / scalar(sum(rate(firehose_counter_event_route_emitter_http_route_nats_messages_emitted_total[24h])))"
    }
   ]
  },
  {
   "title": "Receipt % 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(firehose_counter_event_gorouter_registry_message_route_emitter_total[48h])+rate(firehose_counter_event_gorouter_unregistry_message_route_emitter_total[48h]))) / scalar(sum(rate(firehose_counter_event_route_emitter_http_route_nats_messages_emitted_total[48h])))"
    }
   ]
  },
  {
   "title": "Route registry message receipt %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_gorouter_registry_message_route_emitter_total[5m] offset 1m)+rate(firehose_counter_event_gorouter_unregistry_message_route_emitter_total[5m] offset 1m)) / scalar(sum(rate(firehose_counter_event_route_emitter_http_route_nats_messages_emitted_total[5m] offset 1m)))"
    }
   ]
  },
  {
   "title": "Receipt % 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(firehose_counter_event_gorouter_registry_message_route_emitter_total[7d])+rate(firehose_counter_event_gorouter_unregistry_message_route_emitter_total[7d]))) / scalar(sum(rate(firehose_counter_event_route_emitter_http_route_nats_messages_emitted_total[7d])))"
    }
   ]
  },
  {
   "title": "Receipt % 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(firehose_counter_event_gorouter_registry_message_route_emitter_total[30d])+rate(firehose_counter_event_gorouter_unregistry_message_route_emitter_total[30d]))) / scalar(sum(rate(firehose_counter_event_route_emitter_http_route_nats_messages_emitted_total[30d])))"
    }
   ]
  },
  {
   "title": "Reg latency 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_gorouter_ms_since_last_registry_update[24h]))"
    }
   ]
  },
  {
   "title": "Reg latency 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_gorouter_ms_since_last_registry_update[48h]))"
    }
   ]
  },
  {
   "title": "Route registration latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(max_over_time(firehose_value_metric_gorouter_ms_since_last_registry_update[5m]))\n"
    }
   ]
  },
  {
   "title": "Reg latency 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_gorouter_ms_since_last_registry_update[7d]))"
    }
   ]
  },
  {
   "title": "Reg latency 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_gorouter_ms_since_last_registry_update[30d]))"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 22 },
   "content": "# API\n\n## Cloud Controller reliability\n\nIf Cloud Controller is unreliable, then our users will have a bad user experience when interacting with the API (CLI and Pazmin).\n\n_(This measure is suboptimal because the metric is generated by CC not by gorouter - timeouts and bad gateways will not get counted)_\n\n## UAA reliability\n\nIf UAA is unreliable, then our users will have a bad user experience when logging in (CLI and Pazmin).\n\n\n_(This measure is suboptimal because the metric is generated by UAA not by gorouter - timeouts and bad gateways will not get counted)_",
   "targets": [
    {}
   ]
  },
  {
   "title": "CC % 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(firehose_value_metric_cc_http_status_5_xx[24h]) or vector(0))\n/\n(\n sum(rate(firehose_value_metric_cc_http_status_5_xx[24h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_4_xx[24h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_3_xx[24h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_2_xx[24h]) or vector(0))\n)\n)"
    }
   ]
  },
  {
   "title": "CC % 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(firehose_value_metric_cc_http_status_5_xx[48h]) or vector(0))\n/\n(\n sum(rate(firehose_value_metric_cc_http_status_5_xx[48h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_4_xx[48h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_3_xx[48h]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_2_xx[48h]) or vector(0))\n)\n)"
    }
   ]
  },
  {
   "title": "Cloud controller API reliability %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (\nsum(rate(firehose_value_metric_cc_http_status_5_xx[5m]) or vector(0))\n/\n(\n sum(rate(firehose_value_metric_cc_http_status_5_xx[5m]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_4_xx[5m]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_3_xx[5m]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_2_xx[5m]) or vector(0))\n)\n)"
    }
   ]
  },
  {
   "title": "CC % 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(firehose_value_metric_cc_http_status_5_xx[7d]) or vector(0))\n/\n(\n sum(rate(firehose_value_metric_cc_http_status_5_xx[7d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_4_xx[7d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_3_xx[7d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_2_xx[7d]) or vector(0))\n)\n)"
    }
   ]
  },
  {
   "title": "CC % 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(firehose_value_metric_cc_http_status_5_xx[30d]) or vector(0))\n/\n(\n sum(rate(firehose_value_metric_cc_http_status_5_xx[30d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_4_xx[30d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_3_xx[30d]) or vector(0)) +\n sum(rate(firehose_value_metric_cc_http_status_2_xx[30d]) or vector(0))\n)\n)"
    }
   ]
  },
  {
   "title": "UAA % 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1- avg\n(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[24h])\n/\nrate(firehose_value_metric_uaa_requests_global_completed_count[24h]))"
    }
   ]
  },
  {
   "title": "UAA % 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1- avg\n(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[48h])\n/\nrate(firehose_value_metric_uaa_requests_global_completed_count[48h]))"
    }
   ]
  },
  {
   "title": "UAA API reliability %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1- avg\n(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[5m])\n/\nrate(firehose_value_metric_uaa_requests_global_completed_count[5m]))"
    }
   ]
  },
  {
   "title": "UAA % 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 31 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1- avg\n(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[7d])\n/\nrate(firehose_value_metric_uaa_requests_global_completed_count[7d]))"
    }
   ]
  },
  {
   "title": "UAA % 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 31 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1- avg\n(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[30d])\n/\nrate(firehose_value_metric_uaa_requests_global_completed_count[30d]))"
    }
   ]
  },
  { "title": "Scheduling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
   "content": "# Scheduling\n\nWhen a user has an app (long-running-process or LRP) or runs a task (eg `cf run-task`) this has to be placed on a cell (server which runs apps and tasks). An auction is held to allocate a task or a LRP to a cell.\n\n## Auction reliability %\n\nWhat % of auctions which are started do not fail. Auctions are important because if an auction cannot be fulfilled, users' tasks and apps cannot run.",
   "targets": [
    {}
   ]
  },
  {
   "title": "Auction % 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg((\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total[24h]) + \nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total[24h])\n)\n/\n(\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total[24h]) +\nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total[24h])\n))"
    }
   ]
  },
  {
   "title": "Auction % 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg((\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total[48h]) + \nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total[48h])\n)\n/\n(\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total[48h]) +\nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total[48h])\n))"
    }
   ]
  },
  {
   "title": "Auction reliability %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg((\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total[5m]) + \nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total[5m])\n)\n/\n(\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total[5m]) +\nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total[5m])\n))"
    }
   ]
  },
  {
   "title": "Auction % 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 38 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg((\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total[7d]) + \nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total[7d])\n)\n/\n(\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total[7d]) +\nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total[7d])\n))"
    }
   ]
  },
  {
   "title": "Auction % 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 38 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg((\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total[30d]) + \nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_total[30d])\n)\n/\n(\nrate(firehose_counter_event_auctioneer_auctioneer_lrp_auctions_started_total[30d]) +\nrate(firehose_counter_event_auctioneer_auctioneer_task_auctions_started_total[30d])\n))"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 44 },
   "content": "# Logging\n\n## RLP egress reliability %\n\nMeasures `egress / (dropped + egress)` as a percentage. If this is too unreliable then logs will not get through to consumers.\n\n## Syslog agent egress reliability %\n\nThe router and diego-cell instances ship logs to syslog consumers. If the syslog agents are too unreliable then logs will not get through to consumers.\n\nA syslog consumer could be a tenant's logging stack, or a SaaS observability service.\n\n_(This is currently unreliably measured due to shortcomings in the firehose exporter)_",
   "targets": [
    {}
   ]
  },
  {
   "title": "RLP 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 44 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_rlp_egress_total[24h])\n/\n(rate(firehose_counter_event_loggregator_rlp_egress_total[24h]) + rate(firehose_counter_event_loggregator_rlp_dropped_total[24h])))"
    }
   ]
  },
  {
   "title": "RLP 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 44 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_rlp_egress_total[48h])\n/\n(rate(firehose_counter_event_loggregator_rlp_egress_total[48h]) + rate(firehose_counter_event_loggregator_rlp_dropped_total[48h])))"
    }
   ]
  },
  {
   "title": "RLP egress reliability %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_rlp_egress_total[5m])\n/\n(rate(firehose_counter_event_loggregator_rlp_egress_total[5m]) + rate(firehose_counter_event_loggregator_rlp_dropped_total[5m])))"
    }
   ]
  },
  {
   "title": "RLP 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_rlp_egress_total[7d])\n/\n(rate(firehose_counter_event_loggregator_rlp_egress_total[7d]) + rate(firehose_counter_event_loggregator_rlp_dropped_total[7d])))"
    }
   ]
  },
  {
   "title": "RLP 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_rlp_egress_total[30d])\n/\n(rate(firehose_counter_event_loggregator_rlp_egress_total[30d]) + rate(firehose_counter_event_loggregator_rlp_dropped_total[30d])))"
    }
   ]
  },
  {
   "title": "Syslog 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 50 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"router|diego-cell\"}[24h])\n/\n(\n  rate(firehose_counter_event_loggregator_syslog_agent_dropped_total[24h])\n  +rate(firehose_counter_event_loggregator_syslog_agent_egress_total[24h])\n))"
    }
   ]
  },
  {
   "title": "Syslog 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 50 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"router|diego-cell\"}[48h])\n/\n(\n  rate(firehose_counter_event_loggregator_syslog_agent_dropped_total[48h])\n  +rate(firehose_counter_event_loggregator_syslog_agent_egress_total[48h])\n))"
    }
   ]
  },
  {
   "title": "Syslog agent egress reliability %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (bosh_job_name) (rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"router|diego-cell\"}[5m])\n/\n(\n  rate(firehose_counter_event_loggregator_syslog_agent_dropped_total[5m])\n  +rate(firehose_counter_event_loggregator_syslog_agent_egress_total[5m])\n))",
     "legendFormat": "{{bosh_job_name}}"
    }
   ]
  },
  {
   "title": "Syslog 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 53 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"router|diego-cell\"}[7d])\n/\n(\n  rate(firehose_counter_event_loggregator_syslog_agent_dropped_total[7d])\n  +rate(firehose_counter_event_loggregator_syslog_agent_egress_total[7d])\n))"
    }
   ]
  },
  {
   "title": "Syslog 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 53 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"router|diego-cell\"}[30d])\n/\n(\n  rate(firehose_counter_event_loggregator_syslog_agent_dropped_total[30d])\n  +rate(firehose_counter_event_loggregator_syslog_agent_egress_total[30d])\n))"
    }
   ]
  },
  { "title": "Service discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 57 },
   "content": "# Service discovery\n\n## Bosh-dns-adapter request time\n\nThe time taken for internal DNS requests to complete, if these requests take too long then services which rely on internal networking may experience timeouts.",
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS ms 24h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 57 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, firehose_value_metric_bosh_dns_adapter_get_i_ps_request_time[24h]))"
    }
   ]
  },
  {
   "title": "DNS ms 48h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 57 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, firehose_value_metric_bosh_dns_adapter_get_i_ps_request_time[48h]))"
    }
   ]
  },
  {
   "title": "Bosh-dns-adapter request time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, firehose_value_metric_bosh_dns_adapter_get_i_ps_request_time[5m]))"
    }
   ]
  },
  {
   "title": "DNS ms 7d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 60 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, firehose_value_metric_bosh_dns_adapter_get_i_ps_request_time[7d]))"
    }
   ]
  },
  {
   "title": "DNS ms 30d",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 60 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, firehose_value_metric_bosh_dns_adapter_get_i_ps_request_time[30d]))"
    }
   ]
  }
 ]
}