{
 "title": "Dodgy cell detector",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(node_role,bosh_deployment)"
    }
   },
   {
    "name": "bosh_job_name",
    "label": "Diego job",
    "query": {
     "query": "label_values(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\".*diego-cell.*\"},bosh_job_name)"
    }
   },
   {
    "name": "bosh_job_id",
    "label": "Diego bosh_job_id",
    "query": {
     "query": "label_values(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"},bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "label": "Diego bosh_job_ip",
    "query": {
     "query": "label_values(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"},bosh_job_ip)"
    }
   },
   {
    "name": "zone",
    "label": "Diego zone",
    "query": {
     "query": "label_values(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"},bosh_job_az)"
    }
   },
   {
    "name": "status_codes_pattern",
    "label": "Request status codes",
    "query": "All : .*, 2xx : 2.., 3xx : 3.., 4xx : 4.., 5xx : 5.."
   },
   {
    "name": "interval",
    "label": "Analysis interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of separate app instances serving [$status_codes_pattern] responses over $interval",
   "type": "timeseries",
   "description": "More than a couple could be a sign of trouble.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    label_replace(\n        present_over_time((\n            (group(firehose_value_metric_rep_container_age{bosh_job_name=~\"$bosh_job_name\", bosh_job_id=~\"$bosh_job_id\", bosh_job_ip=~\"$bosh_job_ip\"}) by (process_instance_id, bosh_job_id, bosh_job_name))\n            * on (bosh_job_id) group_left() (group(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_az=~\"$zone\"}) by (bosh_job_id))\n        )[$interval:]),\n        \"instance_id\",\n        \"$0\",\n        \"process_instance_id\",\n        \".*\"\n    ) * on(instance_id) group_left(process_instance_id) (\n    present_over_time(\n        (group(firehose_http_start_stop_requests{status_code=~\"$status_codes_pattern\"}) by (instance_id))[$interval:]\n    )\n)) by (bosh_job_id, bosh_job_name)",
     "legendFormat": "{{bosh_job_name}}/{{bosh_job_id}}"
    }
   ]
  },
  {
   "title": "Dodgy network event rate ($interval avg)",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "present_over_time(\n  (group(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_az=~\"$zone\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\",bosh_job_name=~\"$bosh_job_name\"}) by (bosh_job_name, bosh_job_id, bosh_job_ip))[$interval:]\n) * on(bosh_job_ip) group_left() label_replace(\n  rate((\n    node_netstat_Tcp_InErrs\n    + on (instance) node_netstat_Udp_InErrors\n    + on (instance) node_netstat_Icmp_InErrors\n    + on (instance) (sum(node_network_receive_errs_total) by (instance))\n    + on (instance) (sum(node_network_transmit_errs_total) by (instance))\n    + on (instance) (sum(node_network_carrier_changes_total) by (instance))\n  )[$interval:]),\n  \"bosh_job_ip\",\n  \"$1\",\n  \"instance\",\n  \"([^:]+).*?\"\n)",
     "legendFormat": "{{bosh_job_name}}/{{bosh_job_id}}"
    }
   ]
  },
  {
   "title": "[$status_codes_pattern] response serving rate (avg $interval)",
   "type": "timeseries",
   "description": "Short surges of 5xx may be a single app going wrong, bad cells are likely to have extended increased error rates and stand out from the others.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time(\n    (\n        sum(\n            label_replace(\n                present_over_time((\n                    (group(firehose_value_metric_rep_container_age{bosh_job_name=~\"$bosh_job_name\", bosh_job_id=~\"$bosh_job_id\", bosh_job_ip=~\"$bosh_job_ip\"}) by (process_instance_id, bosh_job_id, bosh_job_name))\n                    * on (bosh_job_id) group_left() (group(node_role{bosh_deployment=~\"$bosh_deployment\",bosh_job_az=~\"$zone\"}) by (bosh_job_id))\n                )[$interval:]),\n                \"instance_id\",\n                \"$0\",\n                \"process_instance_id\",\n                \".*\"\n            ) * on(instance_id) group_left(process_instance_id)\n            (sum(firehose_http_start_stop_requests{status_code=~\"$status_codes_pattern\"}) by (instance_id))\n        ) by (bosh_job_id, bosh_job_name) / 60\n    )[$interval:]\n)",
     "legendFormat": "{{bosh_job_name}}/{{bosh_job_id}}"
    }
   ]
  }
 ]
}