{
 "title": "Doppler heatmaps",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_doppler_subscriptions, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_doppler_subscriptions, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_doppler_ingress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_doppler_egress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Dropped ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_doppler_dropped_total{direction=\"ingress\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Dropped ingress over period",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event_loggregator_doppler_dropped_total{direction=\"ingress\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Dropped egress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_doppler_dropped_total{direction=\"egress\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Dropped egress over period",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event_loggregator_doppler_dropped_total{direction=\"egress\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_doppler_subscriptions{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  }
 ]
}