{
 "title": "Forwarder agents",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_forwarder_agent_ingress_total, bosh_job_name)"
    }
   },
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_forwarder_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\"}, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_forwarder_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_forwarder_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Origin Mappings",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_forwarder_agent_origin_mappings_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])*60"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_forwarder_agent_dropped_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0"
    }
   ]
  },
  {
   "title": "Dropped over period",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event_loggregator_forwarder_agent_dropped_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Avg envelope size",
   "type": "heatmap",
   "description": "Actually a metric of the \"loggregator agent\", downstream from the \"forwarder agent\", but figure should be similar.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_metron_average_envelopes{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  }
 ]
}