{
 "title": "grootfs",
 "tags": [
  "cf",
  "garden"
 ],
 "time": { "from": "2021-08-17T05:23:21.066Z", "to": "2021-08-20T14:10:28.354Z" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_value_metric_grootfs_exclusive_locking_time, bosh_job_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bosh_job_ephemeral_disk_percent{bosh_job_id=~\"${bosh_job_id}\", bosh_job_name=\"diego-cell\"}",
     "legendFormat": "pct"
    },
    {
     "expr": "firehose_value_metric_grootfs_committed_quota_in_bytes{bosh_job_id=~\"${bosh_job_id}\", bosh_job_name=\"diego-cell\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "firehose_value_metric_grootfs_unused_layers_size{bosh_job_id=~\"${bosh_job_id}\", bosh_job_name=\"diego-cell\"}",
     "legendFormat": "unusedlayers"
    },
    {
     "expr": "firehose_value_metric_grootfs_downloaded_layers_size_in_bytes{bosh_job_id=~\"${bosh_job_id}\", bosh_job_name=\"diego-cell\"}",
     "legendFormat": "downloadedlayers"
    }
   ]
  },
  {
   "title": "Time spent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_grootfs_download_time{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_image_clean_time{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_image_creation_time{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_image_deletion_time{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_unpack_time{bosh_job_id=\"${bosh_job_id}\"}"
    }
   ]
  },
  {
   "title": "Locking Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_grootfs_exclusive_locking_time{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_shared_locking_time{bosh_job_id=\"${bosh_job_id}\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_grootfs_memory_stats_num_bytes_allocated_heap{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_memory_stats_num_bytes_allocated_stack{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_memory_stats_num_mallocs{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_memory_stats_num_frees{bosh_job_id=\"${bosh_job_id}\"}"
    }
   ]
  },
  {
   "title": "CPUs/goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firehose_value_metric_grootfs_num_cpus{bosh_job_id=\"${bosh_job_id}\"}"
    },
    {
     "expr": "firehose_value_metric_grootfs_num_go_routines{bosh_job_id=\"${bosh_job_id}\"}"
    }
   ]
  }
 ]
}