{
 "title": "Log cache",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_value_metric__log_cache_uptime, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_value_metric__log_cache_uptime, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event__log_cache_ingress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event__log_cache_egress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Send failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event__log_cache_send_failures_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0",
     "legendFormat": "{{bosh_job_ip}}"
    }
   ]
  },
  {
   "title": "Send failures over period",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event__log_cache_send_failures_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Expiry",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event__log_cache_expired_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Truncation duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "firehose_value_metric__log_cache_truncation_duration{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Cache period",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "firehose_value_metric__log_cache_cache_period{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  }
 ]
}