{
 "title": "Reverse Log Proxy",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_rlp_subscriptions, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_rlp_subscriptions, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_rlp_ingress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_rlp_egress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_rlp_dropped_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0",
     "legendFormat": "{{bosh_job_ip}} {{direction}}"
    }
   ]
  },
  {
   "title": "Dropped over period",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event_loggregator_rlp_dropped_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_rlp_subscriptions{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Rejected streams",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_rlp_rejected_streams_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Log router connections",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "firehose_counter_event_loggregator_rlp_log_router_connects_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"} - firehose_counter_event_loggregator_rlp_log_router_disconnects_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  }
 ]
}