{
 "title": "Service Operation Levels",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "% URL Uptime",
   "type": "stat",
   "description": "provides uptime of cf api, cf rtr and paas-admin",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(pingdom_uptime_status{hostname=\"api.__SYSTEM_DNS_ZONE_NAME__\"}[$__range])",
     "legendFormat": "cf api"
    },
    {
     "expr": "100 * avg_over_time(pingdom_uptime_status{hostname=\"admin.__SYSTEM_DNS_ZONE_NAME__\"}[$__range])",
     "legendFormat": "paas-admin"
    },
    {
     "expr": "100 * avg_over_time(pingdom_uptime_status{hostname=\"healthcheck.__APPS_DNS_ZONE_NAME__\",name=\"PaaS HTTPS - prod-lon\"}[$__range])",
     "legendFormat": "cf apps"
    }
   ]
  },
  {
   "title": "Cell Utilisation Rate",
   "type": "timeseries",
   "description": "Shows the percentage of memory of a Diego Cell",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(bosh_job_mem_percent{bosh_job_name=\"diego-cell\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Application Instances Running",
   "type": "timeseries",
   "description": "Number of Application Instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by (environment) (sum_over_time(cf_application_instances_running[1h])) / sum by (environment) (sum_over_time(cf_application_instances[1h])))",
     "legendFormat": "Desired"
    },
    { "legendFormat": "Running" }
   ]
  },
  {
   "title": "HTTP 5xx errors",
   "type": "stat",
   "description": "Average rate of http status 5xx responses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(firehose_value_metric_cc_http_status_5_xx)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average dropped log message rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(firehose_counter_event_loggregator_doppler_dropped_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}