{
 "title": "Service type adoption - __DEPLOY_ENV__",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_type",
    "label": "Service type",
    "query": "label_values(paas_op_services_provisioned_count, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Explainer",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "content": "# Service type adoption dashboard\n\nUse the service type dropdown to choose which service(s) to see.\n\n## The visualisations\nEvery service type has the same 3 visualisations:\n\n1. 7 day change - the number of provisioned service instances compared to 7 days ago\n2. 30 day change -  the number of provisioned service instances compared to 30 days ago\n3. daily change - chart plotting the average, min, and max serivce instances per day over the last 7 days. \n\n"
  },
  { "title": "$service_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "service_type" },
  {
   "title": "${service_type} 7 day change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(sum(avg_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d]))) - floor(sum(avg_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d] offset 7d)))"
    }
   ]
  },
  {
   "title": "Current # of ${service_type} service instances",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(paas_op_services_provisioned_count{type=\"${service_type}\"})"
    }
   ]
  },
  {
   "title": "${service_type} 30 day change",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(sum(avg_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d]))) - floor(sum(avg_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d] offset 30d)))"
    }
   ]
  },
  {
   "title": "daily change in ${service_type} service instances",
   "type": "graph",
   "description": "The average number shows steady, ongoing usage.\n\nMinimums and maximums show activity within a day (e.g. people playing with a backing service, or using it in an ephemeral way)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "# service instances" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(floor(avg_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d]))),\n  \"type\",\n  \"${service_type}\",\n  \"\",\n  \"\"\n)",
     "legendFormat": "Average {{type}} service instances"
    },
    {
     "expr": "label_replace(\n  sum(min_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d])),\n  \"type\",\n  \"${service_type}\",\n  \"\",\n  \"\"\n)",
     "legendFormat": "Minimum {{type}} service instances"
    },
    {
     "expr": "label_replace(\n  sum(max_over_time(paas_op_services_provisioned_count{type=\"${service_type}\"}[1d])),\n  \"type\",\n  \"${service_type}\",\n  \"\",\n  \"\"\n)",
     "legendFormat": "Maximum {{type}} service instances"
    }
   ]
  }
 ]
}