{
 "title": "Syslog agents",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_syslog_agent_ingress_total, bosh_job_name)"
    }
   },
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_syslog_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\"}, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_counter_event_loggregator_syslog_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_syslog_agent_ingress_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_syslog_agent_egress_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Dropped messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_syslog_agent_messages_dropped_per_drain_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) > 0",
     "legendFormat": "{{bosh_job_name}} {{bosh_job_ip}} {{drain_scope}}→{{drain_url}}"
    }
   ]
  },
  {
   "title": "Dropped messages over period",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_counter_event_loggregator_syslog_agent_messages_dropped_per_drain_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "Drains",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_syslog_agent_drains{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Binding refreshes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_syslog_agent_binding_refresh_count_total{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m]) * 60"
    }
   ]
  },
  {
   "title": "Last binding refresh latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_syslog_agent_latency_for_last_binding_refresh{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Active Drains",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_syslog_agent_active_drains{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Invalid Drains",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_syslog_agent_invalid_drains{bosh_job_name=~\"$bosh_job_name\",bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  }
 ]
}