{
 "title": "Trafficcontroller",
 "tags": [
  "cf",
  "loggregator"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bosh_job_id",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_trafficcontroller_doppler_proxy_app_streams, bosh_job_id)"
    }
   },
   {
    "name": "bosh_job_ip",
    "query": {
     "query": "label_values(firehose_value_metric_loggregator_trafficcontroller_doppler_proxy_app_streams, bosh_job_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_trafficcontroller_ingress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_trafficcontroller_egress_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Doppler Proxy Recent Logs Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_trafficcontroller_doppler_proxy_recent_logs_latency{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Doppler Proxy App Streams",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_trafficcontroller_doppler_proxy_app_streams{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_trafficcontroller_query_error_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Doppler Proxy Firehoses",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "firehose_value_metric_loggregator_trafficcontroller_doppler_proxy_firehoses{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}"
    }
   ]
  },
  {
   "title": "Doppler Proxy Slow Consumers",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_slow_consumer_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  },
  {
   "title": "Doppler Proxy Log Cache Failures",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "rate(firehose_counter_event_loggregator_trafficcontroller_doppler_proxy_log_cache_failure_total{bosh_job_id=~\"$bosh_job_id\",bosh_job_ip=~\"$bosh_job_ip\"}[10m])"
    }
   ]
  }
 ]
}