{
 "title": "Usage by organisation",
 "description": "AKA \"who's to blame?\". Ignores orgs used for tests etc.",
 "tags": [ "cf" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(bosh_job_healthy, environment)"
    }
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
    }
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
    }
   },
   {
    "name": "diego_bosh_job_name",
    "label": "Diego Job",
    "query": {
     "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\".*diego-cell.*\"}, bosh_job_name)"
    }
   },
   {
    "name": "status_codes_pattern",
    "label": "Request status codes (rate)",
    "query": "All : .*, 2xx : 2.., 3xx : 3.., 4xx : 4.., 5xx : 5.."
   },
   {
    "name": "methods_pattern",
    "label": "Request methods",
    "query": {
     "query": "label_values(firehose_http_start_stop_server_request_duration_seconds_sum, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total container memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(firehose_container_metric_memory_bytes_quota{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$diego_bosh_job_name\"}) by (application_id) * on(application_id) group_right group(cf_application_info{organization_name!~\"[A-Z]+-.*\"}) by (application_id, organization_name)) by (organization_name)",
     "legendFormat": "{{ organization_name }}"
    }
   ]
  },
  {
   "title": "Total container start rate (approx)",
   "type": "timeseries",
   "description": "Lacking a real (and sufficiently-labeled) metric for containers being started, this actually measures the number of very young containers attributable to an organization.\n\nA surge of apparent container starts *could* indicate a lot of crashes and attempted restarts.\n\nAttempted container starts that don't even manage to live for a minute will probably get missed from this plot.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(count(min_over_time(firehose_value_metric_rep_container_age{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$diego_bosh_job_name\", organization_name!~\"[A-Z]+-.*\"}[8m]) < (2 * 60 * 1e9)) by (organization_name)) / 10",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Total request rate ($status_codes_pattern, $methods_pattern)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(firehose_http_start_stop_requests{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", status_code=~\"$status_codes_pattern\", method=~\"$methods_pattern\"}[5m])) by (application_id) * on(application_id) group_right group(cf_application_info{organization_name!~\"[A-Z]+-.*\"}) by (application_id, organization_name)) by (organization_name)",
     "legendFormat": "{{ organization_name }}"
    }
   ]
  },
  {
   "title": "Total container instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count(firehose_container_metric_memory_bytes_quota{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$diego_bosh_job_name\"}) by (application_id) * on(application_id) group_right group(cf_application_info{organization_name!~\"[A-Z]+-.*\"}) by (application_id, organization_name)) by (organization_name)",
     "legendFormat": "{{ organization_name }}"
    }
   ]
  },
  {
   "title": "Total log rate",
   "type": "timeseries",
   "description": "Doesn't include logs from gorouter, which will be approximately proportional to the request rate.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(firehose_value_metric_rep_log_rate{organization_name!~\"[A-Z]+-.*\",environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", bosh_job_name=~\"$diego_bosh_job_name\"}) by (organization_name)",
     "legendFormat": "{{ organization_name }}"
    }
   ]
  },
  {
   "title": "Total request time ($methods_pattern)",
   "type": "timeseries",
   "description": "Total amount of http connection time used during a time period (i.e. 60 * 1s connections would be 1 minute).\n\nUnit is seconds, but telling grafana that makes it list large values in weeks etc. - not very useful.\n\nSorry, no status-code filtering here.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(firehose_http_start_stop_server_request_duration_seconds_sum{environment=~\"$environment\", bosh_deployment=~\"$bosh_deployment\", method=~\"$methods_pattern\"}) by (application_id) * on(application_id) group_right group(cf_application_info{organization_name!~\"[A-Z]+-.*\"}) by (application_id, organization_name)) by (organization_name)",
     "legendFormat": "{{ organization_name }}"
    }
   ]
  }
 ]
}