{
 "title": "User Impact - __DEPLOY_ENV__",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gorouter requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_total[2m]))",
     "legendFormat": "All Responses"
    },
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_4_xx_total[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_5_xx_total[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "API requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_2_xx[2m]))",
     "legendFormat": "2xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_4_xx[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_5_xx[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "Application Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_running)",
     "legendFormat": "LRPsRunning"
    },
    {
     "expr": "max(firehose_value_metric_bbs_lr_ps_desired)",
     "legendFormat": "LRPsDesired"
    }
   ]
  },
  {
   "title": "UAA requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_2_xx_count[2m]))",
     "legendFormat": "2xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_4_xx_count[2m]))",
     "legendFormat": "4xx Responses"
    },
    {
     "expr": "sum(rate(firehose_value_metric_uaa_requests_global_status_5_xx_count[2m]))",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "Number of cells (last 30 days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"diego-cell\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "ceil(count(firehose_value_metric_rep_capacity_total_memory{bosh_job_name=\"diego-cell\"}) * on () (100 - rep_memory_capacity_pct:avg5m{bosh_job_name=\"diego-cell\"}) / (100 - 33))",
     "legendFormat": "Required"
    }
   ]
  },
  {
   "title": "CloudController Job Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(firehose_value_metric_cc_job_queue_length_total)",
     "legendFormat": "CC Job Queue Length"
    }
   ]
  },
  {
   "title": "Platform Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(ALERTS{alertstate=\"firing\",layer=\"\",alertname!~\"^CFApp.*$\",severity!=\"none\"}) - (avg(alertmanager_alerts{state=\"suppressed\"}) or vector(0))) or vector(0)"
    }
   ]
  },
  {
   "title": "Other Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",layer=~\"^.+$\"}) or vector(0)"
    }
   ]
  }
 ]
}