{
 "title": "User Impact Redux - __DEPLOY_ENV__",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "isoseg",
    "label": "Isolation Segment",
    "query": "label_values(diego_cells_deployed, bosh_job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$isoseg cell utilisation",
   "type": "stat",
   "description": "$isoseg",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "repeat": "isoseg",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(diego_cells_required{bosh_job_name=\"$isoseg\"} / diego_cells_deployed{bosh_job_name=\"$isoseg\"})*100",
     "legendFormat": "Cell utilisation"
    }
   ]
  },
  {
   "title": "$isoseg cell count (30 days)",
   "type": "graph",
   "description": "Number of cells deployed vs number of cells required over the last 30 days.  Used to see trends in cell usage.",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "repeat": "isoseg",
   "yaxes": [
    { "format": "short", "label": "Num cells" }
   ],
   "targets": [
    {
     "expr": "diego_cells_deployed{bosh_job_name=\"$isoseg\"}",
     "legendFormat": "Deployed"
    },
    {
     "expr": "diego_cells_required{bosh_job_name=\"$isoseg\"}",
     "legendFormat": "Required"
    }
   ]
  },
  {
   "title": "Platform Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(ALERTS{alertstate=\"firing\",layer=\"\",alertname!~\"^CFApp.*$\",severity!=\"none\"}) - (avg(alertmanager_alerts{state=\"suppressed\"}) or vector(0))) or vector(0)"
    }
   ]
  },
  {
   "title": "Other Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",layer=~\"^.+$\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Average CloudController Job Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(firehose_value_metric_cc_job_queue_length_total[5m]))",
     "legendFormat": "CC Job Queue Length"
    }
   ]
  },
  {
   "title": "Application instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(firehose_value_metric_bbs_lr_ps_running)",
     "legendFormat": "Running"
    },
    {
     "expr": "avg(firehose_value_metric_bbs_lr_ps_desired)",
     "legendFormat": "Desired"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 }, "options": { "content": "<center><h1>API</h1></center>" } },
  {
   "title": "API requests/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_2_xx[2m]))",
     "legendFormat": "2xx Responses"
    }
   ]
  },
  {
   "title": "API 4xx response rate over 2m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_4_xx[2m]))",
     "legendFormat": "4xx responses"
    }
   ]
  },
  {
   "title": "API 5xx response rate over 2m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_value_metric_cc_http_status_5_xx[2m]))",
     "legendFormat": "4xx responses"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "options": {
    "content": "<center><h1>Gorouter</h1></center>"
   }
  },
  {
   "title": "Gorouter 4xx response rate over 2m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_4_xx_total[2m]))",
     "legendFormat": "4xx responses"
    }
   ]
  },
  {
   "title": "Gorouter requests/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_total[2m]))",
     "legendFormat": "2xx Responses"
    }
   ]
  },
  {
   "title": "Gorouter 5xx response rate over 2m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(firehose_counter_event_gorouter_responses_5_xx_total[2m]))",
     "legendFormat": "4xx responses"
    }
   ]
  }
 ]
}