# copied from Dockerfile of from jruby:9.2-alpine
FROM eclipse-temurin:8-jdk-focal

RUN apt-get update && apt-get install -y libc6-dev make --no-install-recommends && rm -rf /var/lib/apt/lists/*

ENV JRUBY_VERSION 9.2.21.0
ENV JRUBY_SHA256 dbf05fca4f61bd7d5131d9b83c5f4d1a249213c474b82def37e82013969c8b8a
RUN mkdir /opt/jruby \
  && curl -fSL https://repo1.maven.org/maven2/org/jruby/jruby-dist/${JRUBY_VERSION}/jruby-dist-${JRUBY_VERSION}-bin.tar.gz -o /tmp/jruby.tar.gz \
  && echo "$JRUBY_SHA256 /tmp/jruby.tar.gz" | sha256sum -c - \
  && tar -zx --strip-components=1 -f /tmp/jruby.tar.gz -C /opt/jruby \
  && rm /tmp/jruby.tar.gz \
  && update-alternatives --install /usr/local/bin/ruby ruby /opt/jruby/bin/jruby 1
ENV PATH /opt/jruby/bin:$PATH

# skip installing gem documentation
RUN mkdir -p /opt/jruby/etc \
  && { \
  echo 'install: --no-document'; \
  echo 'update: --no-document'; \
  } >> /opt/jruby/etc/gemrc

RUN gem install bundler -v 2.3.26
RUN gem install rake net-telnet xmlrpc

# don't create ".bundle" in all our apps
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_SILENCE_ROOT_WARNING=1 \
  BUNDLE_APP_CONFIG="$GEM_HOME"
ENV PATH $GEM_HOME/bin:$PATH
# adjust permissions of a few directories for running "gem install" as an arbitrary user
RUN mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME"

# From here is our custom stuff

RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

ARG LOGSEARCH_FOR_CLOUDFOUNDRY_TAG
RUN cd /tmp && git clone https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry.git \
    && cd logsearch-for-cloudfoundry \
    && git checkout ${LOGSEARCH_FOR_CLOUDFOUNDRY_TAG} \
    && cd src/logsearch-config \
    && rm Gemfile.lock \
    && bundle install \
    && bundle exec rake build

ARG LOGSEARCH_BOSHRELEASE_TAG
RUN wget -q -O /tmp/redact_passwords.conf "https://raw.githubusercontent.com/cloudfoundry-community/logsearch-boshrelease/${LOGSEARCH_BOSHRELEASE_TAG}/src/logsearch-config/src/logstash-filters/snippets/redact_passwords.conf"\
    && wget -q -O /tmp/syslog_standard.conf "https://raw.githubusercontent.com/cloudfoundry-community/logsearch-boshrelease/${LOGSEARCH_BOSHRELEASE_TAG}/src/logsearch-config/src/logstash-filters/snippets/syslog_standard.conf"

WORKDIR /tmp/logsearch-for-cloudfoundry/src/logsearch-config
